name: riseup_assignment
description: Riseup Assignment Flutter Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_builder: ^0.4.2
  get: ^4.3.8
  get_storage: ^2.0.3
  fluttertoast: ^8.0.8
  flutter_svg_provider: ^1.0.3
  extended_image: ^6.0.2+1
  dio: ^4.0.6
  google_fonts: ^2.1.0
  cached_network_image: any
  loading_indicator: ^3.0.2
  carousel_slider: ^4.0.0
  dotted_line: ^3.1.0
  flutter_automation: ^2.0.0
  device_info: ^2.0.3
  easy_splash_screen: ^1.0.3
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.3.0
  connectivity_plus: ^2.3.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  fade_shimmer: ^2.0.1
  swipeable_tile: ^2.0.0+1
  intl: ^0.17.0
  flutter_icons:
    git:
      url: https://github.com/Sayed-Siam123/flutter-icons-master.git
      ref: master



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  device_preview:
    git:
      url: https://github.com/monkeydaichan/flutter_device_preview.git
      path: device_preview
      ref: master


dependency_overrides:
  platform: ^3.1.0
  flutter_math_fork: ^0.6.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
